1 de 9,005
(sin asunto)
Recibidos

LUIS PEDRO MUÑOZ RUIZ <lmunozr3@miumg.edu.gt>
1:10 p.m. (hace 4 minutos)
para mí

version: '3.7'

services:
  moodle:
    build: .
    ports:
      - "8080:80"
    environment:
      MOODLE_DBTYPE: mysqli
      MOODLE_DBHOST: db
      MOODLE_DBNAME: moodle
      MOODLE_DBUSER: moodle
      MOODLE_DBPASS: moodle
    volumes:
      - moodledata:/var/www/moodledata
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - db_data:/var/lib/mysql

volumes:
  moodledata:
  db_data: